//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.1
//     from Assets/Inputs/TouchInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @TouchInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @TouchInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""TouchInput"",
    ""maps"": [
        {
            ""name"": ""TouchControl"",
            ""id"": ""9d2eb54c-ee8f-4c0a-aff7-8466aa76423e"",
            ""actions"": [
                {
                    ""name"": ""touch"",
                    ""type"": ""Value"",
                    ""id"": ""043b7f2b-13a3-40f0-81f6-39c281f9d85c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d2937344-59fd-43e6-bfd8-140bf8da8a46"",
                    ""path"": ""<Pointer>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""touch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // TouchControl
        m_TouchControl = asset.FindActionMap("TouchControl", throwIfNotFound: true);
        m_TouchControl_touch = m_TouchControl.FindAction("touch", throwIfNotFound: true);
    }

    ~@TouchInput()
    {
        Debug.Assert(!m_TouchControl.enabled, "This will cause a leak and performance issues, TouchInput.TouchControl.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // TouchControl
    private readonly InputActionMap m_TouchControl;
    private List<ITouchControlActions> m_TouchControlActionsCallbackInterfaces = new List<ITouchControlActions>();
    private readonly InputAction m_TouchControl_touch;
    public struct TouchControlActions
    {
        private @TouchInput m_Wrapper;
        public TouchControlActions(@TouchInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @touch => m_Wrapper.m_TouchControl_touch;
        public InputActionMap Get() { return m_Wrapper.m_TouchControl; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchControlActions set) { return set.Get(); }
        public void AddCallbacks(ITouchControlActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchControlActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchControlActionsCallbackInterfaces.Add(instance);
            @touch.started += instance.OnTouch;
            @touch.performed += instance.OnTouch;
            @touch.canceled += instance.OnTouch;
        }

        private void UnregisterCallbacks(ITouchControlActions instance)
        {
            @touch.started -= instance.OnTouch;
            @touch.performed -= instance.OnTouch;
            @touch.canceled -= instance.OnTouch;
        }

        public void RemoveCallbacks(ITouchControlActions instance)
        {
            if (m_Wrapper.m_TouchControlActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchControlActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchControlActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchControlActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchControlActions @TouchControl => new TouchControlActions(this);
    public interface ITouchControlActions
    {
        void OnTouch(InputAction.CallbackContext context);
    }
}
